project_id = "qermxzepyzbenemcordv"

[functions.create-admin]
verify_jwt = false

[functions.check-refund-status]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-booking-acceptance-email]
verify_jwt = false

[functions.send-daily-report-reminder]
verify_jwt = false
