project_id = "qermxzepyzbenemcordv"

[functions.check-incomplete-onboarding]
verify_jwt = false

[functions.stripe-connect-webhook]
verify_jwt = false

[functions.test-all-emails]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.manual-send-booking-notification]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.check-refund-status]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-booking-acceptance-email]
verify_jwt = false

[functions.send-daily-report-reminder]
verify_jwt = false

[functions.send-police-vet-reminder]
verify_jwt = false

[functions.stripe-connect-onboarding]
verify_jwt = true

[functions.stripe-connect-account-status]
verify_jwt = true

[functions.process-booking-payout]
verify_jwt = false

[functions.cleanup-stale-payments]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

